### ISSUE TITLE
Update Worklog entry to have option to look up issues not assigned to me

### ISSUE THREAD

**Issue by EH-DUMAC** [shridhar-tl/jira-assistant#100]
When adding a worklog entry, the ticket no. field only finds tickets currently assigned to me, or are specifically configured in My Bookmarks.  This is fine 95% of the time, but can a button be added to expand search?

Our issue is that we get support tickets added to us frequently, but the Jira ticket doesn't always get assigned, at least not right away.  So nearly every time we have to go look it up in Jira to get the ticket number, or get it assigned, and then come back to JA and enter ticket number, or refresh the page to pick up new assignments.

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC,
This issue has been resolved by addition an option to add custom JQL for these suggestions in Advanced Settings page. Their are no options to add a like search in Jira for ticket number. And doing a dynamic search with summary while user type in field cause performance issue as most of the time Jira doesn't provide the result for jql so quickly.

I will look into other options to implement this functionality, but as of now changing the JQL for expanded search is possible.

**Comment by EH-DUMAC** [comment]
Thanks, and I do understand the performance hit, which is why I was hoping for a button or something that would use the advanced query only when needed.

I see the new default and user query fields, but it is not letting me edit it to try it out.  Is there an option I need to enable somewhere to allow changing the advance settings?

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC, For the fields currently exists, default query is not editable. But for individual instance you can edit it. Start typing and it will work. Their are more settings planned and will be added in future enhancements. For some of the fields default may be editable. But for these cases it is not editable.

**Comment by EH-DUMAC** [comment]
Yep, I figured the default field would not be editable, but for some reason I could not type in to the user field either yesterday.  Today I was able to edit it, and it appears to be working, however I would still prefer a way to run the advanced query only when needed.  Something like a button, or some kind of toggle, or even some keyboard shortcut, on the worklog input screen.  I suppose the suggestion list could even display something like "Use Advanced/Custom Search (Ctrl+/)".  Can such an option also be added to the worklog screen?

**Comment by shridhar-tl** [comment]
Sure, will look into it. I leave this ticket open for tracking.

**Comment by EH-DUMAC** [comment]
I had a PC issue, that I think led to the JA Extension getting corrupted in Chrome, so I had to reinstall it.  I am not sure if it was this, or the newer version, but I can no longer see the user fields on the advanced settings page to be able to insert the query I was previously using.

Was something changed in the latest version?

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC - Their was some configuration issue which occurred for users who newly installed the app in past two weeks. This was already resolved, but since a week due to chrome's new process, any updates are taking more than 5 days to get reviewed and published. Hence that fix is not yet available for Chrome users. But once your version gets updated to v0.92, you can reinstall and check if the issue is resolved. As chrome's new review process is taking longer now a days, I couldn't provide any quick fix. It takes atleast a week for any new fix / changes to be available for end users.

I understand this is frustrating, but I am helpless at this moment and I am thinking of a way to overcome this challenge

**Comment by EH-DUMAC** [comment]
I see the version updated to .92 today, however I still do not see the user fields on the advanced settings page.  Only two columns are shown in this list, the Settings column, and the Default column.  So I do not see where I can set a custom Ticket suggestions JQL.

**Comment by shridhar-tl** [comment]
Hi @EH-DUMAC - As mentioned earlier, as of now the fix is available only if you re-install after 0.92 is available. If you want the fix to be available immediately, **you can reinstall and it will start working**. Else you will have to wait for few more days.

I analysed a way to reduce the review time and found an option. By removing the default permission required, review would get completed soon. I hope this would let me to publish changes immediately. I will have to try to publish a new version and confirm it.

Apologies for all the inconvenience.

**Comment by EH-DUMAC** [comment]
Thanks for the prompt replies, and sorry, I missed that you said I could reinstall after new version was released.  I now see the new user fields, and thus far appears to be working as needed.

Just for reference, I am using the following as my custom JQL for Ticket suggestions:
project in ("A", "B", "C", "D") AND resolution = Unresolved AND status != Closed AND (assignee = currentUser() OR assignee is EMPTY) ORDER BY assignee, key

**Comment by vhladiienko** [comment]
> And doing a dynamic search with summary while user type in field cause performance issue as most of the time Jira doesn't provide the result for jql so quickly.

@shridhar-tl What I did in my app is created 2 autocomplete inputs: one for a project and the other one for issues. Issues were looked up with `project = 'TEST'` JQL and cached locally. The cache was updated every time a project was changed. You can add a debounce time on top of that to update issue list less frequently. Then the dynamic issue search would look into cache. You can always add a tiny refresh button somewhere next to the menu.

**Comment by shridhar-tl** [comment]
Hi @vhladiienko @EH-DUMAC - Issue lookup in Add Worklog popup is enhanced and all the reported issues including #111  should be resolved now. Hence closing this issue. The changes would be available from v2.44 which would be published by this week end.
