### ISSUE TITLE
Import issue, custom field of type Select List (single choice)

### ISSUE THREAD

**Issue by jenscski** [shridhar-tl/jira-assistant#134]
I'm trying to import issues to a project with a custom field of type **Select List (single choice)**.

But I'm not able to add a valid value to the csv file, so I can't import any issues to the project.

Is this a bug, or is is possible to import when a custom field needs a value?

**Comment by shridhar-tl** [comment]
@jenscski - I will look into this and see if this is implementable. I cannot assure you any dates when this would be available. But I will try to have it implemented by next week end.

**Comment by jenscski** [comment]
Look at my PR, I think I fixed it with that one.

> @jenscski - I will look into this and see if this is implementable. I cannot assure you any dates when this would be available. But I will try to have it implemented by next week end.

**Comment by shridhar-tl** [comment]
@jenscski - Your PR is already merged, but due to issue mentioned in #139 I was still not able to publish the changes yet. Will try to publish it within this weekend.

**Comment by shridhar-tl** [comment]
This would be resolved or tracked as part of #219. Hence closing this issue.
