### ISSUE TITLE
401 Unauthenticated page is shown even after being authenticated with Jira

### ISSUE THREAD

**Issue by shridhar-tl** [shridhar-tl/jira-assistant#214]
Some times when you try to access Jira Assistant, you may not be able to access it and 401 Unauthenticated error page is displayed as shown in following screenshot:

![image](https://user-images.githubusercontent.com/37339683/172989047-349ae316-b3f2-4ba1-acbb-ca8345325fa7.png)

**Reasons:** Primarily their are 3 known reasons for this error to happen and are as follows:
1) You are not authenticated with Jira in same browser. To ensure if you are authenticated just click on "Open Jira url" button from the screen and see if Jira opens and you were able to access it.
2) Your company has blocked access to Jira API's and hence this tool was not able to access the API's. If others in your company is able to use Jira Assistant or if you were able to use Jira Assistant when you reinstall, then this may not likely be the case and can be ignored.
3) Some how permission for the extension to access Jira Url is revoked. Look at the details below to grant permission for Jira Assistant.

**Check if Permission is granted for Jira Assistant:**
1. Look at the console and see if their are any warnings about the permission like "Permission not granted for ***" as shown in below screenshot:
![image](https://user-images.githubusercontent.com/37339683/172995196-e3a61323-d99f-47d0-a064-67560496e3cf.png)

2. Go to extension details page and see if Site access permission is revoked like shown in following screenshots. Note both the below screenshot represent that the extension access to Jira is revoked:
![image](https://user-images.githubusercontent.com/37339683/172995558-4b8f1b81-6198-4faf-bdb1-9dde9227e3cd.png)
(or)
![image](https://user-images.githubusercontent.com/37339683/172995823-9c6a8911-77a2-4476-8acc-25b319e3f9f8.png)

If you see any of the above mentioned issue, then it means either you or your organization has revoked access to the extension intentionally or unintentionally. This could have happened due to some other extenal settings / installations as well. To resolve this issue grant access to extension by following one of the way shown below.

**Granting Permission for Jira Assistant:**
You will have to grant access to all the Jira servers you integrate with Jira Assistant. Their are two ways to grant access to extension.

1. Simple but less secured way is to grant access to all the sites just by selecting "On all sites" under "Site access" like shown in following screenshot:
![image](https://user-images.githubusercontent.com/37339683/172996631-5ac0eaab-0392-4968-8238-04b904f09beb.png)

2. Most secured and recommended way is to individually grant access to each and every Jira Server you integrate with Jira Assistant. To do that select "On specific sites" under "Site access" and add all the Jira Server root url. This would provide access only to the mentioned sites and is more secure.
![image](https://user-images.githubusercontent.com/37339683/172997059-c7d71b46-bab0-49a3-a1c7-4d2cf686e6fc.png)

Note: In Chrome, to open extension details page, right click on JA icon in your browser and click Manage extension.

**Comment by shridhar-tl** [comment]
This issue has been resolved and would be available with Jira Assistant v2.37. But this update would be installed only for chrome users above v102. Hence if any of you are using older version of chrome, you are requested to upgrade to latest version of chrome which is also recommended for your safe browsing.

**Comment by shridhar-tl** [comment]
This fix is available in Jira Assistant v2.37 and is available for users of Chrome v102.x. Kindly update your browser before trying to upgrade to latest version of JA.

**Comment by lweisberg** [comment]
I have chrome 103, and latest JA, but I am still getting this error.  When I look at Console the only thing I see is the below and my only recourse is to remove the extension and add it back in:

DevTools failed to load source map: Could not load content for chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/index.04954243.js.map: System error: net::ERR_FILE_NOT_FOUND

index.04954243.js:2 Chrome Browser service injected

index.04954243.js:2 Settings already migrated

DevTools failed to load source map: Could not load content for chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/502.fe1cc893.chunk.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by shridhar-tl** [comment]
Hi @lweisberg -  Their are more details provided in my initial post above to check for the permission. Have you looked at it? If not next time when the issue happens, please have a look at it and see if that is the case for you.

Additionally, you mentioned your chrome version is 103, but what is your Jira Assist version? It should be v2.37 or higher.

**Comment by shridhar-tl** [comment]
Hi @lweisberg - If this issue happens again, kindly provide your console screenshot. So far no one has ever provided any console screenshot of the 401 page when this issue happend.

Moreover I forgot to mention this last time: The fix provided is to show an additional button to grant access to that Url and the fix does not prevent this issue from happening. Instead if it happens, you need not reinstall the extension, instead just click on this grant access button and the permission would be granted for the extension. But why this permission is getting removed for some user is still unknown and so I was not able to provide any solution for that:
![image](https://user-images.githubusercontent.com/37339683/178770141-afcee50c-8978-4cea-af89-d8003e7c9a3d.png)

**Comment by lweisberg** [comment]
Thanks.. I'll keep it in mind, but I am pretty sure they I tried clicking
on grant permission... Should they have popped up dinner kind of login page?

**Comment by lweisberg** [comment]
Hi - I got the 401 yesterday but clicking on the grant permission remedied
the issue.  I am also sending you some screen captures from that time.  I
hope it helps,

[image: image.png]

Click on Grant permission:
\
[image: image.png]
I was then brought successfully to the JA dashboard.

Thanks!
Larry

**Comment by novosirj** [comment]
Oh man, I wish I had seen this sooner. I had one Mac on macOS Catalina with JA 2.33 that I've just replaced that did this constantly, and I never found a way to deal with it other than uninstalling and reinstalling the extension. I still have it around though, and it happened constantly, so I can get you logs from the next time.

**Comment by shridhar-tl** [comment]
Hi @lweisberg - Happy to know "Grant permission"  button resolves your issue. So that confirms, permission is getting removed for some users and of course how it gets removed is something hard to find. But as far the click of button resolves the issue, we should be good going with it.

Additionally, in your previous comment you mentioned you are attaching screenshots. But I don't see any screenshots. Anyway, as we could confirm its the permission issue, I don't think console screenshots would help further. Initially I asked for screenshot only in case where permission is not an issue.

**Comment by shridhar-tl** [comment]
Hi @novosirj , no issues. Just ensure you are using the latest version of Jira Assistant (v2.38 as on date) and you try to Grant Permission as mentioned above. If issues is still not resolved, then console screenshot may help identifying the root cause.

**Comment by shridhar-tl** [comment]
Assuming this issue is resolved, closing this issue. If anyone else face it again, please reopen this issue with console screenshot.

**Comment by lweisberg** [comment]
Thanks - I'll check next time it happens, but it has happened many times in
the past half year or so, and I've never had any issues with logging into
jira itself.
Larry

**Comment by timjosborn** [comment]
![Screen Shot 2022-10-11 at 4 35 57 PM](https://user-images.githubusercontent.com/12085582/195193264-1168a6a9-a417-4595-bf56-64e021fc6fa3.png)
![Screen Shot 2022-10-11 at 4 36 36 PM](https://user-images.githubusercontent.com/12085582/195193336-6ad8ae77-0ed2-4dde-888a-be6189f43fc7.png)
I'm getting the error as discussed above, but when I click the 'Grant Access' button I just get the same error page. I'm on JA v.2.39 and Chrome Version 106.0.5249.103 (Official Build) (arm64) MacOs 12.6
JA has worked fine for me in the past but I haven't used it in probably a month and now I get this message. I'm going to try reinstalling it and see if that works.

**Comment by shridhar-tl** [comment]
Hi @timjosborn - First of all, you are using old version of JA. Current version is v2.41. Please update to the latest version so that you get lots of bug fixes and new features added in this version.

**Comment by timjosborn** [comment]
> Hi @timjosborn - First of all, you are using old version of JA. Current version is v2.41. Please update to the latest version so that you get lots of bug fixes and new features added in this version.

Thank you! It seems to be working fine on 2.41.

**Comment by nothing-personal-gh** [comment]
@shridhar-tl I am getting a CORS error. This is not discussed already in this thread. Is there a workaround for this? Below is the full error:

> Access to fetch at 'https://MY_SITE.atlassian.net/rest/api/2/myself' from origin 'chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I tried https://app.jiraassistant.com/ too. I get 200 but gets redirected to 401 page. There are no errors in the Network tab too.

**Comment by nothing-personal-gh** [comment]
I solved the about CORS issue by using the oAuth2 option from the https://app.jiraassistant.com website. I disabled the Chrome extension to use the oAuth 2 option.

**Comment by nothing-personal-gh** [comment]
I think it could be related to the fact that my organization has blocked all addons on Chrome.

**Comment by lweisberg** [comment]
For various reasons I've not been using Jira for past year or so, but recently came back and I am getting the 401 error when trying to use JA web (https://app.jiraassistant.com/)... I no longer see a Grant Permission button....

I looked at console and see this (seem unable to paste or attach screen capture..) - does this indicate an issue that my company is blocking access? :

JA: Auth result:

{authenticated: false, jiraUrl: 'https://xxxxx.atlassian.net/', needIntegration: undefined}

authenticated

:

False

![image](https://github.com/shridhar-tl/jira-assistant/assets/8721582/56584fd2-8edb-49db-b1f4-da2d3218e0b3)

**Comment by lweisberg** [comment]
Turns out that our IT blocks using/installing the extension.  As far as the web version, all I needed to od was the delete any JA cookies first.

**Comment by 50064060** [comment]
<img width="566" height="448" alt="Image" src="https://github.com/user-attachments/assets/4c4885bd-98c9-441d-9d29-1b5e917394f4" />

facing the issue

**Comment by egorn-tech** [comment]
Hi everyone! I faced with same issue (( 
Please kindly clarify  how to fix it ?
And the second problem is that JA stopped seeing projects. Version 2.58

<img width="1895" height="845" alt="Image" src="https://github.com/user-attachments/assets/09a9442f-0efb-4cbf-8752-1d9c4b7be8f5" />

**Comment by diogocostaonenetwork** [comment]
Hi,

I'm experiencing the 401 Unauthenticated screen, but the reason seems to be different to the one mentioned in this issue. I can typically open the app, but after a while I get this screen:

<img width="1712" height="850" alt="Image" src="https://github.com/user-attachments/assets/e1510f0a-d1f5-45b6-9938-a0a927c4e438" />

Looking at the network tab, the app seem to be attempting to refresh the token:

<img width="870" height="809" alt="Image" src="https://github.com/user-attachments/assets/2a418ecc-2e0c-4840-89a6-215acd5dfa60" />

<img width="1022" height="378" alt="Image" src="https://github.com/user-attachments/assets/f85c3d60-59c5-4ff8-a5fd-8117424bd552" />

I can clear the storage and log in again, but I lose all settings. Would it be possible to add a "re-login" button or something?

I'm using the Web application, no extension.

And thanks for this great tool!

**Comment by wrockett-CAI** [comment]
I'm getting a 401 as well, but, only in the Web, authentication is coming back as false.  In the extension, it works.  Clicking in the extension to goto the web gives a 401.
