### ISSUE TITLE
Ticket search not respecting configured JQL query

### ISSUE THREAD

**Issue by hhofstaetter** [shridhar-tl/jira-assistant#249]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.44

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Linux

### Bug Description

A custom query for ticket suggestions is defined in the settings of jira assistant. The issue search in the worklog calendar does not respect that query and always uses an empty query to search for issues. 

Could this be related to the changes here?
https://github.com/shridhar-tl/jira-assistant/blob/4ee2f2b268b7f6fa5a80cb64cab927fdeac0de9a/src/services/jira-service.js#L439 

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
@hhofstaetter - Yes you are right and this is a known behavior. At this point using this JQL would cause some unexpected behavior. So once everywhere in the application, this new picker is used, then everywhere the JQL suggestion would be used. Most probably this would happen in next release.

Until then, all the issues would be selectable from the picker.

**Comment by hhofstaetter** [comment]
@shridhar-tl 
Thank you for the feedback. I downgraded the addon to 2.43 for now, that makes the search usable for me again.

**Comment by shridhar-tl** [comment]
@hhofstaetter - This issue has been resolved and would be available in upcoming release. However it would immediately be available in Web version of JA if you want to try.

Closing this ticket considering the issue is resolved

**Comment by hhofstaetter** [comment]
@shridhar-tl
My problems are not resolved. The api request is now using the JQL as configured, but its still getting other results then the previous issue picker.

The previous issue picker allowed Sub-Tasks to be returned, the implementation now does not return any Sub-Tasks.

The api resource needs the GET parameter showSubTasks=true to return any subtasks.
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-search/

Would it be possible to set that parameter or to make it configurable?

**Comment by githubdarren** [comment]
@shridhar-tl

all users are no longer receiving subtask suggestions in the ticket number field when entering non-ticket-number text, e.g. words from the summary. JA does retrieve the correct subtask when we type the subtask ticket number. Also, it is suggesting all parent tickets where before it showed only open tickets assigned to that user.

If this isn't related, I'm happy to create a new ticket

**Comment by hhofstaetter** [comment]
@shridhar-tl 
Works now in the app. Thank you.

**Comment by shridhar-tl** [comment]
@githubdarren - you can control the list of tickets shown using the Suggestion JQL from Advanced settings page. This is actually an enhancement done to pull all the tickets in suggestion based on feedback form multiple users since last few years.
