### ISSUE TITLE
Custom Columns in Worklog

### ISSUE THREAD

**Issue by BobbieZain** [shridhar-tl/jira-assistant#291]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.48

### What browser are you using?

Edge

### Feature Suggestion

Adding support to display custom columns in the worklog report, as our tickets are further grouped with custom fields like "Booking Code" shown on this picture.
![image](https://user-images.githubusercontent.com/128392753/226365853-f7919985-8622-42cc-9e1b-89a4ce742731.png)
![image](https://user-images.githubusercontent.com/128392753/226366677-13331686-34ce-421c-8669-8cd1ccb018d7.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @BobbieZain - This implementation is done and is already available in Web version of Jira Assistant. This would be published to extension as part of JA v2.49 in next couple of weeks max. Until then if you would like to try it to see if it works as expected, you can try it out in Web version by accessing https://app.jiraassistant.com

**Comment by shridhar-tl** [comment]
Hi @BobbieZain - Did you get a chance to have a look at it in Web version?

**Comment by shridhar-tl** [comment]
This issue has been resolved and hence closing this ticket. Please feel free to reopen it if you have any other queries.

**Comment by jockie** [comment]
This works nicely for some field types (like "Text Field (single line)"), thanks!

What still does not work for me is adding custom fields that are of type "Select List (single choice)", unfortunately.

**Comment by jockie** [comment]
Seems this has been fixed together with #331 in v2.58.
